apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ras
  name: ras
spec:
  containers:
  - image: nginx
    name: ras
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
